version: '3.8'

services:
  file-watcher:
    build: 
      context: .
      dockerfile: dockerfile-watcher
    container_name: file-watcher
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./public/files:/app/files
    working_dir: /app
    command: ["python", "src_py/watcher.py"]
    restart: always
    depends_on:
      - portal-web
    networks:
      - my-network

  portal-web:
    build: 
      context: .
      dockerfile: dockerfile-portal
    container_name: portal-web
    volumes:
      - ./public:/app/public
      - ./prisma/database:/app/prisma/database
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "start"]
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge