# Usa uma imagem mínima do Python
FROM python:3.10-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos Python para o container
COPY ./src_py ./src_py
COPY ./prisma ./prisma

COPY ./src_py/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt
