# Usa uma imagem mínima do Python
FROM python:3.10-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos Python para o container
COPY ./src_py ./src_py
COPY ./prisma ./prisma
